### ISSUE TITLE
Allocation keeps submitting jobs when `--time-request` > `--time-limit`

### ISSUE THREAD

**Issue by mbercx** [It4innovations/hyperqueue#248]
Hi! First let me echo @giovannipizzi's sentiment in #241: HyperQueue looks to be exactly what we need to implement task farming in AiiDA, and it's super lightweight, fast and easy to use. Kudos!

I've noticed something strange as I was running on our debug queue, however. It seems that if you set up an allocation with a short time limit, and start submitting HQ jobs that request a longer time, HQ keeps on starting more jobs on Slurm. Take for example the following allocation:

```console
$ hq alloc list
+----+--------------+-------------------+-----------+---------+------+--------------------------------+
| ID | Backlog size | Workers per alloc | Timelimit | Manager | Name | Args                           |
+----+--------------+-------------------+-----------+---------+------+--------------------------------+
| 2  | 1            | 1                 | 30m       | SLURM   | test | --partition=debug,-A,mr0,-C,mc |
+----+--------------+-------------------+-----------+---------+------+--------------------------------+
```

If I submit the following HQ job:

```console
$ hq submit --time-request=60m 'echo hello'
Job submitted successfully, job ID: 147
```

HQ keeps on submitting new Slurm jobs until I cancel the HQ job. So after a minute, I already have about ten jobs running:

```console
$ squeue -u mbercx
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
            518832     debug hq-alloc   mbercx  R       0:47      1 nid001884
            518833     debug hq-alloc   mbercx  R       0:42      1 nid001885
            518834     debug hq-alloc   mbercx  R       0:37      1 nid001886
            518835     debug hq-alloc   mbercx  R       0:32      1 nid001887
            518836     debug hq-alloc   mbercx  R       0:27      1 nid001888
            518837     debug hq-alloc   mbercx  R       0:21      1 nid001889
            518838     debug hq-alloc   mbercx  R       0:17      1 nid001890
            518839     debug hq-alloc   mbercx  R       0:12      1 nid001891
            518840     debug hq-alloc   mbercx  R       0:06      1 nid001892
            518841     debug hq-alloc   mbercx  R       0:02      1 nid001893
```

**Comment by Kobzol** [comment]
Thanks for the report! The automatic allocation behaviour of HQ is currently very crude and definitely could be improved. We want to gather usage patterns from users to find how it should be improved.

In your case, HQ sees that there is a job that wasn't assigned to a worker yet. It then tries to fill the Slurm queue with jobs to provide workers. However, in this case the provided workers cannot actually execute the job, since they know that they will only live for 30 minutes, while the job requires workers that will live for at least 60 minutes.

In a general case, it might be difficult to fully solve this issue, since it might not always be possible for the auto-allocator to recognize whether the spawned worker will be able to execute jobs that are currently waiting for a worker.

However, in this specific case, it should actually be quite easy. The automatic allocator knows the time request of the waiting job(s), and it also knows the timelimit of the existing allocation queue. So HQ spawning Slurm allocations here is a bug, we'll fix it.
