### ISSUE TITLE
Starting hq server process directly without bash

### ISSUE THREAD

**Issue by goxeq** [It4innovations/hyperqueue#280]
When I tried to start hq server like this:  ```qsub -A XXX -q qlong -l select=1:ncpus=128:mpiprocs=1,walltime=144:00:00 -- /apps/all/HyperQueue/0.6.0/hq worker start``` it exited with errors:

```
[2022-01-04T15:04:29.463Z INFO  hyperqueue::worker::start] Starting hyperqueue worker 0.6.0
[2022-01-04T15:04:29.463Z INFO  hyperqueue::worker::start] Connecting to: login2.karolina.it4i.cz:45240
thread 'main' panicked at 'Could not get PBS timelimit: No such file or directory (os error 2)', crates/hyperqueue/src/worker/start.rs:425:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

However, when I ran your recommended (https://docs.it4i.cz/general/capacity-computing/) input:  ```qsub -A XXX -q qlong -l select=1:ncpus=128:mpiprocs=1,walltime=144:00:00 -- /bin/bash -l -c "$(which hq) worker start"``` it was working ok.

I find this behaviour unexpected.

**Comment by Kobzol** [comment]
Hi. I agree that it's unfortunate, however this is caused by PBS behaviour (at least it behaves like this on the IT4I clusters).

When you run a command directly after `--`, for some reason the launched script will not have access to `qstat` and `qsub`, which are necessary for proper functionality of the worker and the autoalloc process. It's probably caused by some bash login scripts not being sourced or something like that.

I'll try to find out if this could be circumvented somehow.

**Comment by Kobzol** [comment]
Yes, so it's caused by `/etc/profile` not being sourced. Without explicitly using bash, I don't think that you can easily source that script and then run the command. I tried using `qsub -V`, which should forward all environment variables to the job, but that didn't work.

Have you tried using the [automatic allocator](https://it4innovations.github.io/hyperqueue/stable/deployment/allocation/)? With it you don't have to care about manual PBS usage and worker spawning.

**Comment by goxeq** [comment]
Then it seems like this is beyond the scope of hq. Because you have no way of knowing how much time the worker has left without access to qstat, you would have to send the job id (which is set in the PBS environment) to the server and the server would have to query qstat and send the info back to worker. 

I see that this might be beyond the scope of this program. (However, I also find it conceptually simpler to do all interaction with the PBS system on the server side, rather than letting clients talk to PBS directly. The $PBS_JOBID could be sent from the worker to server when the server first connects - maybe you already do it - and then server would use qstat. But then again, if the client is running in a completely different computing facility, this would not be possible, so I see why you went with your solution of client querying the sever directly). Thank you for looking into this.

**Comment by Kobzol** [comment]
We consider this to be a limitation (quite annoying one, I have to say) of how PBS executes the launched script. We could of course try to find paths to `qstat` dynamically from the worker, but that would be quite brittle and probably would break very soon.

Clients, server and workers can run completely independently of PBS, so we don't want to have a lot of specific PBS functionality. We support PBS job allocation through the automatic allocator subsystem and workers can find out PBS information if they detect a PBS environment, that's it for now.
