### ISSUE TITLE
HyperQueue creates hundreds of thousands directories per day

### ISSUE THREAD

**Issue by svatosFZU** [It4innovations/hyperqueue#294]
On Monday, I have noticed that my space at Karolina ran out of entries quota. I found out that it is because of high number of directories and jobs in .hq-server. On Monday evening, I erased everything there. On Tuesday morning, I checked and saw the same problem again. I had 643 jobs in HyperQueue (all in WAITING state):

[svatosm@login1.karolina ~]$ ml HyperQueue;hq jobs|grep bash|wc -l
643

But the .hq-server dir contained over 70k dirs

[svatosm@login1.karolina ~]$ ll .hq-server/001/autoalloc/1/|wc -l
70398

Each dir contains only one file (hq_submit.sh) with content similar to

#!/bin/bash
#PBS -l select=1
#PBS -N hq-alloc-1
#PBS -o /home/svatosm/.hq-server/001/autoalloc/1/70034/stdout
#PBS -e /home/svatosm/.hq-server/001/autoalloc/1/70034/stderr
#PBS -ADD-13-2 -qqfree

/apps/all/HyperQueue/0.6.0/hq worker start --idle-timeout 5m --manager pbs --server-dir /home/svatosm/.hq-server/001

Checking now, I am at 300k entries. I don't know if it is related to the fact that our project is still waiting for extension, i.e. we cannot submit jobs (but I would assume in that case, HyperQueue would stop trying to send jobs).

Michal Svatos

**Comment by Kobzol** [comment]
HyperQueue currently tries to allocate jobs as often as possible if automatic allocation is enabled. If the allocation fails, this will indeed produce a lot of files.
We will implement some expontential backoff mechanism shortly and add it to the next version, so that the automatic allocator doesn't spam PBS and the disk.

But in this case I would be interested in the reason why the allocation fail in the first place. If the allocation cannot succeed at all, why do you use automatic allocation? You should probably turn off the HyperQueue server until you know that the allocations can succeed.

**Comment by svatosFZU** [comment]
I was using the HyperQueue and the allocation queue until the end of December. Then our project expired. I kept the HyperQueue running because I did not know this is going to happen (at least none of the hq commands I used showed anything suspicious). Only when I was unable to create a file, I started investigating. 
As a workaround, stopping the HyperQueue is natural thing (and it is done now). So, this is more of a question of what is expected behaviour. If I try to do qsub, it returns Access denied. So, it submission persistently fails, why keep trying to submit jobs?

**Comment by Kobzol** [comment]
I see. Indeed, there should be some mechanism for delaying the submission of jobs when it fails too often.

On the other hand, it probably shouldn't just stop right away, PBS can just be temporarily offline or some user limits might be overstepped, but these things can be temporary and HQ should be able to recover (thus it tries again, although currently it does that too often). Even the "access denied" error which you got (and which seems to be permanent) can actually disappear once your projects gets reimbursed with more hours.

The automatic allocation process is asynchronous and runs in the background, so it's also a bit difficult to let the user know that there might be some problems that require their attention.

I suppose that we will implement an exponential backoff for now, and if it's not enough, we can also turn off the submission altogether e.g. if there are too many fails and the situation seems desperate.

@spirali thoughts?

**Comment by Kobzol** [comment]
Another option could be to try to proactively delete the created files on the disk, and keep e.g. only the last X directories for debugging. If the same submission fails 1000 times in a row, there don't need to be so many files created on the disk.

**Comment by svatosFZU** [comment]
I agree. If the HyperQueue just keeps "pinging" the batch then there is no problem. I don't know if exponential decay is the best (as there could be significant time gaps at later stages). Another option would be just keep trying once per minute and ramp up if it succeeds.

**Comment by svatosFZU** [comment]
Deletion of already used files would be also needed (even if the submission works). I was around 10-20k entries at the end of December. So, I would sooner or later  get in the same kind of problem, just few weeks/months later.

**Comment by Kobzol** [comment]
By the way, could you tell us more about your usecase? We are interested in gathering use-cases for HQ and using them to improve its behaviour. You can contact us at `jakub.beranek@vsb.cz`.

**Comment by svatosFZU** [comment]
Sure. I will send some summary to that email.

**Comment by Kobzol** [comment]
Thanks :) For now, we have added support for deleting directories of allocations that weren't submitted [here](https://github.com/It4innovations/hyperqueue/pull/296). Once it gets merged, you can access try it with a [nightly build](https://github.com/It4innovations/hyperqueue/releases) (until we release a new version).

Removing directories of allocations that **were** submitted successfully is more complicated, since these can contain useful data for the user (not just debugging information, but in theory also the actual output of the computation). However, it seems that if you use the automatic allocation subsystem to spawn a lot of PBS/Slurm allocations, the number of files/directories will keep increasing quite a lot. You would have the same problem if you used PBS/Slurm manually, but it should probably be handled better in HyperQueue.

We'll think about it and I'll keep this issue open to post further updates.

**Comment by Kobzol** [comment]
Configurability indeed sounds reasonable, we'll discuss it and probably add some configuration value. Thanks for your input!

Also FYI, you don't have to wait for IT4I to install new versions if you want to try them. HQ is distributed as a single binary, so you can just download (e.g. using `wget`) a prebuilt binary from [here](https://github.com/It4innovations/hyperqueue/releases). The prebuilt binaries should be compatible with IT4I clusters.

New binaries are published on this page for every released version, and also every night with the most current version from the `main` branch.

**Comment by svatosFZU** [comment]
Just to confirm, the problem with directories from failed submissions filling disk is solved in the nightly. I used hq-nightly-2022-01-12-d127f469dca5573f05e98370d65b508c10b33d79-linux-x64.tar.gz, started a server and submitted a test job. The number of directories in .hq-server keeps increasing upto about four hundred and then drop to about twenty.

**Comment by Kobzol** [comment]
Great, thanks for testing it out in the wild! Once https://github.com/It4innovations/hyperqueue/pull/298 is merged, the cleanup should also work for finished allocations (i.e. allocations that have been already completed or have failed with an error after submission).
