### ISSUE TITLE
Produce a better error message when running a script without ./ or absolute path

### ISSUE THREAD

**Issue by goxeq** [It4innovations/hyperqueue#311]
When I create a script and I try to submit it like `hq submit script.sh`, the job fails without giving any reasonable error, just 

```
Wait finished in 8ms 286us 671ns: 1 job failed
Some jobs have failed or have been canceled"`
```
After some experimentation I found out that it has to be submitted as `hq submit ./script.sh` 

Could this requirement to include `./ ` be dropped? Or at least give some better error message.

**Comment by Kobzol** [comment]
Hi! This is actually a bit more subtle. I'll first explain why we can't easily prepend `./` to the command and then talk about potential solutions.

HyperQueue will try to execute the command that you pass to it exactly as you would have executed it in your shell. If you just write `script.sh` in your shell, it will most likely also not work.

If we e.g. prepended `./` to the command, or turned the first submitted command to an absolute path, it could change the meaning of the executed command.

For example, let's assume that we submit `hq submit program` from directory `/foo`, set the working directory to `/bar` and we have `program` located at `/baz` in `$PATH`.

- By default, when a worker executes this task, `program` will be looked up in `$PATH`, so `/baz/program` gets executed.
- If we prepended `./`, the worker would instead try to execute `/bar/program`.
- If we made the path absolute (relative to the submit directory), the worker would try to execute `/foo/program`.

We can't foresee the user's intentions, so the safest way is not to preprocess the command in any way.

However, there are two things that are not ideal in the current state:
- The produced error is quite misleading and frankly just bad, we will definitely improve it.
- Similarly to PBS, the user might actually want to submit a script containing directives, which should be immediately parsed by HyperQueue, instead of being lazily executed. In this situation `script.sh` should be fine, because it will be just some path resolved by HyperQueue at the moment of submission. We also plan to implement this (https://github.com/It4innovations/hyperqueue/issues/6).

**Comment by Kobzol** [comment]
We have altered the error message slightly when a command fails to execute:
```
Before: IO error: No such file or directory (os error 2)
After: Error: Cannot execute "test.sh": No such file or directory (os error 2)
```
Is this error message be clearer for you? Or is there more information that you would like to see here?

**Comment by goxeq** [comment]
The most helpful error message would be:

`Error: Command not found: "test.sh"` optionally, if the file is in working directory and is executable, followed by `Did you mean "./test.sh?"`

Also, where do these error messages go? I don't see them in the command output. I would expect them to go to stderr of the job, but that is empty.

**Comment by Kobzol** [comment]
I suppose that we can add a special error message for such cases where the executable file exists, I'll add it, thanks for the suggestion.

The error message in this case can be displayed using `hq job info <job-id>`.
Because the program wasn't even started (no process was created), no `stdout` and `stderr` was produced and therefore it's empty/missing.

I suppose that we could also output this error to the `stderr` file, but I'm not sure if that's a good idea, because then it could seem like the error was produced during the execution of the submitted program, while in reality the program was never executed in the first place.

The distinction is whether `stdout`/`stderr` should represent the output of the HQ task or the executed program itself (the difference is very subtle, but important in this case). Currently, it is the latter. @spirali thoughts?
