### ISSUE TITLE
Longer name support

### ISSUE THREAD

**Issue by Nortamo** [It4innovations/hyperqueue#482]
Name of a job is currently capped to 40 at `crates/hyperqueue/src/client/commands/submit/command.rs`.

Would it be possible to increase this limit or is it safe to change just in that one place (or is it also set somewhere else?) and compile HQ from source?

**Comment by Kobzol** [comment]
This check was introduced more as a sanity check than anything else, the value `40` is arbitrary. If you need it, we can increase the limit, e.g. to 256 characters or some other number. (I don't think that the check is set anywhere else, so you could recompile from source, but that seems unnecessary, we can increase the limit in the next version if you have a use-case for it).

Out of curiosity, what do you store in the name so that you need more than 40 characters?

**Comment by Nortamo** [comment]
Fixing the limit to e.g 256 would be nice, should probably be sufficient.

We are helping some researchers run larger genomic workflows using nextflow + hyperqueue, and they have quite long descriptive names for the jobs to follow the progress, e.g "integrity_coverage_XXXXX-{DATE}_{some_identifier}_{some_other_identifier}".

Generally it's just a way to more easily follow individual executions in produces logs as one
can use nextflows `tag` attribute to annotate processes so they are not just enumerated in the logs.

So instead of having 

```
Submitted process sayHello (1)
Submitted process sayHello (2)
Submitted process sayHello (3)
```
You could have
```
Submitted process sayHello (argument=Hello)
Submitted process sayHello (argument=Hola)
Submitted process sayHello (argument=Bonjour)
```

in the logs
