### ISSUE TITLE
Feature: Show summary in job logs

### ISSUE THREAD

**Issue by ghuls** [It4innovations/hyperqueue#545]
It would be nice to have some summary in e.g. job list and other output.
e.g. total number of jobs, number of jobs finished, canceled, ...

```
hq job list --all
```

**Comment by Kobzol** [comment]
Good idea. To be honest, we rather discourage users from creating a large amount of jobs, as this is not the intended use-case for HQ (rather, there should be fewer jobs, each with a lot of tasks), so some jobs reporting interfaces are not that nice.

We have discussed this and we would like to propose adding a `hq job summary` command that will display a short table with the amount of jobs in various states, rather than putting more stuff into the existing commands.
