### ISSUE TITLE
Allocation queue draining 

### ISSUE THREAD

**Issue by svatosFZU** [It4innovations/hyperqueue#575]
Hi,
I would like to ask if it is possible to drain allocation queue into another allocation queue. The motivation is as follows:

Our project has a grant on Karolina which is almost used up. After it is gone, it is still possible to continue using the resources on Karolina but under different batch queue. Right now, I have allocation queue set up and used. When the allocated nodehours become exhausted and job submission is no longer possible, the allocation queue will auto pause (if I understand correctly). As the allocation queue parameters cannot be changes on-the-fly (as far as I know), the only way to do the change (which I know of) would be to remove old allocation queue and create a new one to different batch queue. That means all the jobs waiting in the old allocation queue will be lost, which is quite wasteful.
As the jobs are already in the HyperQueue, would it be possible to just move them to a different allocation queue? Ideally, I would wish to be able to do it on per-job basis, i.e. to have something like "hq job migrate" which would take jobID and IDs of two allocation queues. When executed, it would just remove the job from one and put it in the other allocation queue. That way I could decide which jobs to move (if some are not worth the effort), if I would have more allocation queues, I could decide in which one it should run, etc.

**Comment by Kobzol** [comment]
Hi, the ability to modify the parameters of an existing allocation queue could be added, but it's currently a bit low priority for us, because we haven't seen any real use-case for it so far.

I'm not sure if I understand the mentioned motivation. There is no mapping between *HyperQueue jobs* and PBS/Slurm allocations, nor between HQ jobs and allocation queues, these things are completely separated. So it doesn't really make sense to "migrate" a job from one queue to another, as there is nothing to migrate.

I assume that what you meant was taking already submitted PBS allocations and moving them between to a different HQ allocation queue. That could be done, in theory, but it's a rather complex operation and I don't see any use-case for it.

I think that you should just create a new allocation queue and delete the old one. Running out of resources is a very rare event, you most likely do not get a new computational project more often than every month (and even that would be quite often). So cancelling the allocation queue shouldn't be a problem. I wonder what you mean by "quite wasteful" - if the allocations aren't currently executing, it should be OK to just cancel them and resubmit new ones into a different queue. If the allocations are running already and you do not want to cancel them, you do not have to, you can just create a new allocation queue that uses the new PBS queue, pause the old one (or wait until it is auto-paused), so that it does not submit any new allocations, and once the old one runs out of running allocations, then you could simply delete it (or keep it paused forever, that doesn't really matter).

**Comment by svatosFZU** [comment]
OK, maybe I misunderstood the association of hq job and allocation queue. So, to be specific:
Current allocation queue was made using

hq alloc add pbs --backlog 20 --time-limit 40h -- -AOPEN-27-57 -qqcpu

when that runs out, I will need to change submission from qcpu to qcpu_free, i.e. I will make a new allocation queue with

hq alloc add pbs --backlog 20 --time-limit 40h -- -AOPEN-27-57 -qqcpu_free

Will the hq jobs, that were submitted before the change, start running in the new allocation queue?

**Comment by Kobzol** [comment]
Yes :) HQ jobs are completely independent of allocation queues, there is no explicit association. You can provide HQ computing resources (workers) by any means - e.g. starting them manually from a compute node with a manually submitted PBS allocation, or by starting them automatically from PBS allocations created by HQ. This will create computational resources for HQ, and HQ will then try to schedule jobs/tasks that are not finished yet to the available HQ workers. But there is no explicit association - the only thing that will be "matched" are the resource requirements of individual tasks (e.g. "I need 2 CPUs and 1 GPU") and the resources provided by individual workers (e.g. "I have 128 CPUs and 8 GPUs").

If no workers are available, HQ will wait until some workers appear. If a worker crashes (e.g. because an allocation ends/fails) while it was computing a task, the task will be later rescheduled to a different worker.

You can submit a HQ job today, and add a new allocation queue tomorrow, and the tasks of the job will start to execute on the allocations from the new queue once they are ready. Or you could do it in the opposite way, create an allocation queue and then add HQ jobs later.

**Comment by svatosFZU** [comment]
OK, great. Just one question about the matching: 
If I would define the second queue now, what would happen? They are both identical from resource point of view. The difference is only in batch queue name. So, would HyperQueue start sending jobs to both?

**Comment by svatosFZU** [comment]
Also, if the jobs are independent from the allocation queue, it means that I can remove the allocation queue and jobs will stay in the HyperQueue, right?

**Comment by Kobzol** [comment]
> If I would define the second queue now, what would happen? They are both identical from resource point of view. The difference is only in batch queue name. So, would HyperQueue start sending jobs to both?

Yes, the auto allocator would submit PBS allocations for both queues, and HQ would then send jobs to workers coming from allocations from both queues.

If you delete the allocation queue(s), HQ jobs will not be affected. They will remain in the server, waiting for computing resources.
