### ISSUE TITLE
Unable to open hq dashboard subcommand

### ISSUE THREAD

**Issue by jiang-yuha0** [It4innovations/hyperqueue#725]
I'm running on hq 0.19.0
When I try to run `hq dashboard`, an error was displayed.
```
$ hq dashboard
error: unrecognized subcommand 'dashboard'
```

**Comment by Kobzol** [comment]
Hi, we have temporarily [removed](https://github.com/It4innovations/hyperqueue/blob/main/CHANGELOG.md#0190) the dashboard in `0.19.0`, because we made a large internal refactoring and we did not have enough time to get the dashboard working for this release.

We plan to re-enable the dashboard, and add new features to it, in a future release, probably sometime later this year. If you do need the dashboard, feel free to use `0.18.0`.

**Comment by jiang-yuha0** [comment]
Thanks!
